START_IMAGE = "assets/itberloga_spring.jpg"
CATALOG_IMAGE = "assets/catalog_spring.jpg"
GPT_IMAGE = "assets/chatgpt_spring.jpg"
INFO_IMAGE = "assets/info_spring.jpg"
GEMINI_IMAGE = "assets/gemini_spring.jpg"
PERPLEXITY_IMAGE = "assets/perplexity_spring.jpg"
PROFILE_IMAGE = "assets/profile_spring.jpg"